version: '3'

services:
  db:
    build: .
    container_name: master-mysql-8.0
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./MySQLTuner-perl:/MySQLTuner
      - ./debug:/debug
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: ****

  adminer:
    image: adminer
    container_name: db-management-tool
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
